#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Jan 18 22:13:01 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.BeerMakerMenu = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(101, "Quit", "Terminate the program", wx.ITEM_NORMAL)
        self.BeerMakerMenu.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.BeerMakerMenu)
        # Menu Bar end
        self.BeerMakerStatus = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.BeerMakerToolbars = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_TEXT)
        self.SetToolBar(self.BeerMakerToolbars)
        self.BeerMakerToolbars.AddLabelTool(200, "New Recipe", wx.Bitmap("/home/todd/src/selfassembled/beermaker/img/beer.png", wx.BITMAP_TYPE_ANY), wx.Bitmap("/home/todd/src/selfassembled/beermaker/img/beer.png", wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "New Recipe", "Create a new recipe")
        self.BeerMakerToolbars.AddLabelTool(201, "New Batch", wx.Bitmap("/home/todd/src/selfassembled/beermaker/img/beer.png", wx.BITMAP_TYPE_ANY), wx.Bitmap("/home/todd/src/selfassembled/beermaker/img/beer.png", wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "New Batch", "Create a new batch of an existing recipe")
        self.BeerMakerToolbars.AddLabelTool(202, "Edit Recipe/Batch", wx.Bitmap("/home/todd/src/selfassembled/beermaker/img/beer.png", wx.BITMAP_TYPE_ANY), wx.Bitmap("/home/todd/src/selfassembled/beermaker/img/beer.png", wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "Edit current item", "Edit the current recipe or batch")
        # Tool Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnQuit, id=101)
        self.Bind(wx.EVT_TOOL, self.launchRecipeEditor, id=200)
        self.Bind(wx.EVT_TOOL, self.createBatchFromRecipe, id=201)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("BeerMaker")
        self.BeerMakerStatus.SetStatusWidths([-1])
        # statusbar fields
        BeerMakerStatus_fields = [""]
        for i in range(len(BeerMakerStatus_fields)):
            self.BeerMakerStatus.SetStatusText(BeerMakerStatus_fields[i], i)
        self.BeerMakerToolbars.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnQuit(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `OnQuit' not implemented!"
        event.Skip()

    def launchRecipeEditor(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `launchRecipeEditor' not implemented!"
        event.Skip()

    def createBatchFromRecipe(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `createBatchFromRecipe' not implemented!"
        event.Skip()

# end of class MainFrame


class BeerMaker(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MainFrame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class BeerMaker

if __name__ == "__main__":
    BeerMaker = BeerMaker(0)
    BeerMaker.MainLoop()
