#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Jan 20 21:45:51 2010

import os
import sys
from decimal import Decimal

import wx

from models import Grain, Hop, Yeast, Extract, HoppedExtract, Water, Misc, Mineral, Fining, Spice, Herb
from db import DataStore


# begin wxGlade: extracode
# end wxGlade

newIngredient = os.path.abspath('img/icon.gif')
addInventory = os.path.abspath('img/icon.gif')
viewInventory = os.path.abspath('img/icon.gif')

class IngredientEditor(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: IngredientEditor.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, -1)
        self.panel_5 = wx.Panel(self.panel_2, -1, style=wx.SIMPLE_BORDER|wx.SUNKEN_BORDER|wx.TAB_TRAVERSAL)
        self.panel_4 = wx.Panel(self.panel_2, -1, style=wx.SIMPLE_BORDER|wx.SUNKEN_BORDER|wx.TAB_TRAVERSAL)
        self.panel_3 = wx.Panel(self.panel_2, -1, style=wx.SIMPLE_BORDER|wx.SUNKEN_BORDER|wx.TAB_TRAVERSAL)
        self.panel_1 = wx.Panel(self, -1, style=wx.SIMPLE_BORDER|wx.SUNKEN_BORDER|wx.TAB_TRAVERSAL)
        self.ingredientEditor_statusbar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.ingredientEditor_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_TEXT)
        self.SetToolBar(self.ingredientEditor_toolbar)
        self.ingredientEditor_toolbar.AddLabelTool(100, "New Ingredient", wx.Bitmap(newIngredient,wx.BITMAP_TYPE_ANY), wx.Bitmap(newIngredient,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "New Ingredient", "Add a new ingredient")
        self.ingredientEditor_toolbar.AddSeparator()
        self.ingredientEditor_toolbar.AddLabelTool(101, "Add to Inventory", wx.Bitmap(addInventory,wx.BITMAP_TYPE_ANY), wx.Bitmap(addInventory,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "Add to Inventory", "Add this item to your inventory")
        self.ingredientEditor_toolbar.AddLabelTool(102, "View Inventory", wx.Bitmap(viewInventory,wx.BITMAP_TYPE_ANY), wx.Bitmap(viewInventory,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "View Inventory", "View your inventory")
        # Tool Bar end
        self.topLevelCtrl = wx.ListCtrl(self.panel_1, -1, style=wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)
        self.middleLevelCtrl = wx.ListCtrl(self.panel_1, -1, style=wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)
        self.bottomLevelCtrl = wx.ListCtrl(self.panel_1, -1, style=wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)
        self.label_1 = wx.StaticText(self.panel_3, -1, "Name:")
        self.nameCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.label_2 = wx.StaticText(self.panel_3, -1, "Origin:")
        self.originCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.label_9 = wx.StaticText(self.panel_4, -1, "Color:")
        self.colorCtrl = wx.TextCtrl(self.panel_4, -1, "")
        self.label_9_copy_6 = wx.StaticText(self.panel_4, -1, "Potential:")
        self.potentialCtrl = wx.TextCtrl(self.panel_4, -1, "")
        self.label_9_copy = wx.StaticText(self.panel_4, -1, "Dry Yield Fine Grain")
        self.dyfgCtrl = wx.TextCtrl(self.panel_4, -1, "")
        self.label_9_copy_5 = wx.StaticText(self.panel_4, -1, "Coarse/Fine Difference:")
        self.coarseFineDifferenceCtrl = wx.TextCtrl(self.panel_4, -1, "")
        self.label_9_copy_1 = wx.StaticText(self.panel_4, -1, "Moisture")
        self.moistureCtrl = wx.TextCtrl(self.panel_4, -1, "")
        self.label_9_copy_4 = wx.StaticText(self.panel_4, -1, "Distatic Power:")
        self.diastaticPowerCtrl = wx.TextCtrl(self.panel_4, -1, "")
        self.label_9_copy_2 = wx.StaticText(self.panel_4, -1, "Max in Batch:")
        self.maxInBatchCtrl = wx.TextCtrl(self.panel_4, -1, "")
        self.mustMashCtrl = wx.CheckBox(self.panel_4, -1, "Must Mash")
        self.addAfterBoilCtrl = wx.CheckBox(self.panel_4, -1, "Add After Boil")
        self.label_10 = wx.StaticText(self.panel_5, -1, "Notes")
        self.text_ctrl_1 = wx.TextCtrl(self.panel_5, -1, "", style=wx.TE_MULTILINE)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOOL, self.NewIngredient, id=100)
        self.Bind(wx.EVT_TOOL, self.AddInventory, id=101)
        self.Bind(wx.EVT_TOOL, self.ViewInventory, id=102)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.nameCtrl)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.originCtrl)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.colorCtrl)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.potentialCtrl)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.dyfgCtrl)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.coarseFineDifferenceCtrl)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.moistureCtrl)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.diastaticPowerCtrl)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.maxInBatchCtrl)
        self.Bind(wx.EVT_CHECKBOX, self.ItemChanged, self.mustMashCtrl)
        self.Bind(wx.EVT_CHECKBOX, self.ItemChanged, self.addAfterBoilCtrl)
        self.Bind(wx.EVT_TEXT, self.ItemChanged, self.text_ctrl_1)
        # end wxGlade

        self.PopulateBrowser()


    def __set_properties(self):
        # begin wxGlade: IngredientEditor.__set_properties
        self.SetTitle("Ingredient Editor")
        self.SetSize((512, 793))
        self.ingredientEditor_statusbar.SetStatusWidths([-1])
        # statusbar fields
        ingredientEditor_statusbar_fields = [""]
        for i in range(len(ingredientEditor_statusbar_fields)):
            self.ingredientEditor_statusbar.SetStatusText(ingredientEditor_statusbar_fields[i], i)
        self.ingredientEditor_toolbar.Realize()
        # end wxGlade
        
        self.ItemModified = False
        db = DataStore()

    def __do_layout(self):
        # begin wxGlade: IngredientEditor.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(4, 4, 0, 0)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.topLevelCtrl, 1, wx.ALL|wx.EXPAND, 3)
        sizer_2.Add(self.middleLevelCtrl, 1, wx.ALL|wx.EXPAND, 3)
        sizer_2.Add(self.bottomLevelCtrl, 1, wx.ALL|wx.EXPAND, 3)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.ALL|wx.EXPAND, 6)
        sizer_4.Add(self.label_1, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        sizer_4.Add(self.nameCtrl, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        sizer_4.Add(self.label_2, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        sizer_4.Add(self.originCtrl, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        self.panel_3.SetSizer(sizer_4)
        sizer_3.Add(self.panel_3, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.label_9, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.colorCtrl, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.label_9_copy_6, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.potentialCtrl, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.label_9_copy, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.dyfgCtrl, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.label_9_copy_5, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.coarseFineDifferenceCtrl, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.label_9_copy_1, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.moistureCtrl, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.label_9_copy_4, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.diastaticPowerCtrl, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.label_9_copy_2, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.maxInBatchCtrl, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(sizer_6, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_5.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_8.Add(self.mustMashCtrl, 1, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        sizer_8.Add(self.addAfterBoilCtrl, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 3)
        sizer_5.Add(sizer_8, 0, wx.EXPAND, 0)
        self.panel_4.SetSizer(sizer_5)
        sizer_3.Add(self.panel_4, 0, wx.ALL|wx.EXPAND, 3)
        sizer_9.Add(self.label_10, 0, wx.ALL|wx.ADJUST_MINSIZE, 3)
        sizer_9.Add(self.text_ctrl_1, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 3)
        self.panel_5.SetSizer(sizer_9)
        sizer_3.Add(self.panel_5, 1, wx.ALL|wx.EXPAND, 3)
        self.panel_2.SetSizer(sizer_3)
        sizer_1.Add(self.panel_2, 1, wx.ALL|wx.EXPAND, 3)
        self.SetSizer(sizer_1)
        self.Layout()
        self.SetSize((512, 793))
        # end wxGlade

    def _ClearFields(self):
        pass
        
    def _SaveItem(self):
        if self.ingredientType == "Grain":
            self._SaveGrain()
        
        self.itemModified = False

    def _SaveGrain(self):
        name = self.nameCtrl.GetText()
        origin = self.originCtrl.GetText()
        color = Decimal(self.colorCtrl.GetText()).quantize(SRM_QUANT)
        potential = Decimal(self.potentialCtrl.GetText()).quanitze(SG_QUANT)
        dyfg = Decimal(self.dyfgCtrl.GetText()).quantize(PERCENT_QUANT)
        cfd = Decimal(self.cfdCtrl.GetText()).quantize(PERCENT_QUANT)
        moisture = Decimal(self.moistureCtrl.GetText()).quantize(PERCENT_QUANT)
        diastatic = Decimal(self.diastaticPowerCtrl.GetText()).quantize(Decimal(10) ** -1)
        max_in_batch = Decimal(self.maxInBatchCtrl.GetText()).quantize(PERCENT_QUANT)
        if self.mustMashCtrl.IsChecked():
            mush_mash = True
        else:
            mush_mash = False            
        if self.addAfterBoilCtrl.IsChecked():
            add_after_boil = True
        else:
            add_after_boil = False        
        notes = self.notesCtrl.GetText()   
          
        if self.IngredientID:
            thisGrain = Grain.get(self.IngredientID)
        elif Grain.select(Grain.q.name==name)[0]:
            # pop up dialogue asking to save over currently existing item named such
            pass
        else:
            thisGrain = Grain()
        
        thisGrain.set(name = name, 
            origin = origin, 
            color = color, 
            potential = potential, 
            dry_yield_fine_grain = dyfg, 
            coarse_fine_difference = cfg, 
            moisture = moisture, 
            diastatic_power = diastatic, 
            max_in_batch = max_in_batch, 
            mush_mash = mush_mash, 
            add_after_boil = add_after_boil, 
            notes = notes
        )
        
        self.IngredientID = thisGrain.id


    def PopulateBrowser(self):
        base_list = ['Hops','Grains','Extracts','Yeasts','Miscellaneous']
        base_list.sort()

        for base_type in base_list:
            self.topLevelCtrl.InsertStringItem(sys.maxint, base_type)

    def NewIngredient(self, event): # wxGlade: IngredientEditor.<event_handler>
        if self.itemModified:
            self._SaveItem()
        
        self._ClearField()
        self.ingredientType = "Grain"
        

    def AddInventory(self, event): # wxGlade: IngredientEditor.<event_handler>
        print "Event handler `AddInventory' not implemented!"
        event.Skip()

    def ViewInventory(self, event): # wxGlade: IngredientEditor.<event_handler>
        print "Event handler `ViewInventory' not implemented!"
        event.Skip()

    def ItemChanged(self, event): # wxGlade: IngredientEditor.<event_handler>
        print "Event handler `ItemChanged' not implemented"
        event.Skip()

# end of class IngredientEditor


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    ingredientEditor = IngredientEditor(None, -1, "")
    app.SetTopWindow(ingredientEditor)
    ingredientEditor.Show()
    app.MainLoop()
    SRM_QUANT = Decimal(10) ** -2
    SG_QUANT = Decimal(10) ** -4
    PERCENT_QUANT = Decimal(10) ** -2