#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Jan 19 17:36:50 2010
import os

import wx

# begin wxGlade: extracode
# end wxGlade

icon = os.path.abspath('img/icon.gif')

class RecipeEditor(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RecipeEditor.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_4 = wx.StaticText(self, -1, "Name:", style=wx.ALIGN_RIGHT)
        self.nameCtrl = wx.TextCtrl(self, -1, "")
        self.label_4_copy = wx.StaticText(self, -1, "Type:", style=wx.ALIGN_RIGHT)
        self.combo_box_1 = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY|wx.CB_SORT)
        self.label_4_copy_1 = wx.StaticText(self, -1, "Brewer:", style=wx.ALIGN_RIGHT)
        self.nameCtrl_copy_1 = wx.TextCtrl(self, -1, "")
        self.label_1 = wx.StaticText(self, -1, "Ingredients")
        self.ingredientsCtrl = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.addIngredient = wx.Button(self, wx.ID_ADD, "")
        self.deleteIngredient = wx.Button(self, wx.ID_DELETE, "")
        self.panel_1 = wx.Panel(self, -1, style=wx.SIMPLE_BORDER|wx.TAB_TRAVERSAL)
        self.efficiencyButton = wx.Button(self.panel_1, -1, "Efficiency:")
        self.efficiencyCtrl = wx.TextCtrl(self.panel_1, -1, "")
        self.label_6_copy_5 = wx.StaticText(self.panel_1, -1, "%")
        self.label_6 = wx.StaticText(self.panel_1, -1, "Batch Size:", style=wx.ALIGN_RIGHT)
        self.batchSizeCtrl = wx.TextCtrl(self.panel_1, -1, "")
        self.batchSizeChoiceCtrl = wx.Choice(self.panel_1, -1, choices=["Gal", "l"])
        self.label_6_copy = wx.StaticText(self.panel_1, -1, "Estimated OG:", style=wx.ALIGN_RIGHT)
        self.estimatedOGCtrl = wx.TextCtrl(self.panel_1, -1, "")
        self.label_6_copy_5_copy = wx.StaticText(self.panel_1, -1, "Style:")
        self.label_6_copy_1 = wx.StaticText(self.panel_1, -1, "Estimated FG:", style=wx.ALIGN_RIGHT)
        self.estimatedFGCtrl = wx.TextCtrl(self.panel_1, -1, "")
        self.label_6_copy_5_copy_copy = wx.StaticText(self.panel_1, -1, "Style:")
        self.label_6_copy_2 = wx.StaticText(self.panel_1, -1, "Estimated Color:", style=wx.ALIGN_RIGHT)
        self.estimatedColorCtrl = wx.TextCtrl(self.panel_1, -1, "")
        self.label_6_copy_5_copy_copy_1 = wx.StaticText(self.panel_1, -1, "Style:")
        self.label_6_copy_3 = wx.StaticText(self.panel_1, -1, "Esitmated IBU:", style=wx.ALIGN_RIGHT)
        self.estimatedIBUCtrl = wx.TextCtrl(self.panel_1, -1, "")
        self.label_6_copy_5_copy_copy_2 = wx.StaticText(self.panel_1, -1, "Style:")
        self.label_6_copy_4 = wx.StaticText(self.panel_1, -1, "Bitterness Ratio:", style=wx.ALIGN_RIGHT)
        self.bitternessRatioCtrl = wx.TextCtrl(self.panel_1, -1, "")
        self.label_6_copy_5_copy_copy_3 = wx.StaticText(self.panel_1, -1, "IBU/SG")
        self.panel_1_copy = wx.Panel(self, -1, style=wx.SIMPLE_BORDER|wx.TAB_TRAVERSAL)
        self.label_6_copy_6_copy = wx.StaticText(self.panel_1_copy, -1, "Estimated ABV:", style=wx.ALIGN_RIGHT)
        self.efficiencyCtrl_copy = wx.TextCtrl(self.panel_1_copy, -1, "")
        self.label_6_copy_5_copy_1 = wx.StaticText(self.panel_1_copy, -1, "%")
        self.label_6_copy_6 = wx.StaticText(self.panel_1_copy, -1, "Estimated ABW:", style=wx.ALIGN_RIGHT)
        self.batchSizeCtrl_copy = wx.TextCtrl(self.panel_1_copy, -1, "")
        self.label_6_copy_5_copy_1_copy = wx.StaticText(self.panel_1_copy, -1, "%")
        self.label_6_copy_copy = wx.StaticText(self.panel_1_copy, -1, "Estimated Calories:", style=wx.ALIGN_RIGHT)
        self.estimatedOGCtrl_copy = wx.TextCtrl(self.panel_1_copy, -1, "")
        self.label_6_copy_5_copy_1_copy_1 = wx.StaticText(self.panel_1_copy, -1, "%")
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "&Quit", "Terminate the app", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "&File")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Save", wx.Bitmap(icon,wx.BITMAP_TYPE_ANY), wx.Bitmap(icon,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "New Batch", wx.Bitmap(icon,wx.BITMAP_TYPE_ANY), wx.Bitmap(icon,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "", "")
        # Tool Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.AddIngredient, self.addIngredient)
        self.Bind(wx.EVT_BUTTON, self.DeleteIngredient, self.deleteIngredient)
        self.Bind(wx.EVT_BUTTON, self.CalculateEfficiency, self.efficiencyButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RecipeEditor.__set_properties
        self.SetTitle("Recipe Editor")
        self.SetSize((1024, 786))
        self.batchSizeChoiceCtrl.SetSelection(0)
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = ["frame_1_statusbar"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.frame_1_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RecipeEditor.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1_copy = wx.FlexGridSizer(3, 3, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(7, 3, 0, 0)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.label_4, 0, wx.ALL, 5)
        sizer_4.Add(self.nameCtrl, 1, wx.ALL, 1)
        sizer_4.Add(self.label_4_copy, 0, wx.ALL, 5)
        sizer_4.Add(self.combo_box_1, 1, wx.ALL, 1)
        sizer_4.Add(self.label_4_copy_1, 0, wx.ALL, 5)
        sizer_4.Add(self.nameCtrl_copy_1, 1, wx.ALL, 1)
        sizer_1.Add(sizer_4, 0, wx.ALL|wx.EXPAND, 5)
        sizer_2.Add(self.label_1, 0, wx.LEFT|wx.RIGHT|wx.TOP, 5)
        sizer_1.Add(sizer_2, 0, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        sizer_6.Add(self.ingredientsCtrl, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
        sizer_7.Add(self.addIngredient, 0, wx.ALL, 5)
        sizer_7.Add(self.deleteIngredient, 0, wx.ALL, 5)
        sizer_6.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_5.Add(sizer_6, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
        grid_sizer_1.Add(self.efficiencyButton, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        grid_sizer_1.Add(self.efficiencyCtrl, 1, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_5, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        grid_sizer_1.Add(self.batchSizeCtrl, 1, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.batchSizeChoiceCtrl, 0, 0, 0)
        grid_sizer_1.Add(self.label_6_copy, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_RIGHT, 5)
        grid_sizer_1.Add(self.estimatedOGCtrl, 1, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_5_copy, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_1, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_RIGHT, 5)
        grid_sizer_1.Add(self.estimatedFGCtrl, 1, wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_5_copy_copy, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_2, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_RIGHT, 5)
        grid_sizer_1.Add(self.estimatedColorCtrl, 1, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_5_copy_copy_1, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_3, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_RIGHT, 5)
        grid_sizer_1.Add(self.estimatedIBUCtrl, 1, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_5_copy_copy_2, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_4, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_RIGHT, 5)
        grid_sizer_1.Add(self.bitternessRatioCtrl, 1, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.label_6_copy_5_copy_copy_3, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        self.panel_1.SetSizer(grid_sizer_1)
        sizer_3.Add(self.panel_1, 0, wx.ALL|wx.EXPAND, 5)
        grid_sizer_1_copy.Add(self.label_6_copy_6_copy, 0, wx.RIGHT|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1_copy.Add(self.efficiencyCtrl_copy, 1, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1_copy.Add(self.label_6_copy_5_copy_1, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1_copy.Add(self.label_6_copy_6, 0, wx.RIGHT|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1_copy.Add(self.batchSizeCtrl_copy, 1, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1_copy.Add(self.label_6_copy_5_copy_1_copy, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1_copy.Add(self.label_6_copy_copy, 0, wx.RIGHT|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1_copy.Add(self.estimatedOGCtrl_copy, 1, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1_copy.Add(self.label_6_copy_5_copy_1_copy_1, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        self.panel_1_copy.SetSizer(grid_sizer_1_copy)
        sizer_3.Add(self.panel_1_copy, 0, wx.ALL|wx.EXPAND, 5)
        sizer_5.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def AddIngredient(self, event): # wxGlade: RecipeEditor.<event_handler>
        print "Event handler `AddIngredient' not implemented!"
        event.Skip()

    def DeleteIngredient(self, event): # wxGlade: RecipeEditor.<event_handler>
        print "Event handler `DeleteIngredient' not implemented!"
        event.Skip()

    def CalculateEfficiency(self, event): # wxGlade: RecipeEditor.<event_handler>
        print "Event handler `CalculateEfficiency' not implemented!"
        event.Skip()

# end of class RecipeEditor


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = RecipeEditor(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
