#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Jan 19 23:14:15 2010
import os

import wx

# begin wxGlade: extracode
# end wxGlade

newRecipe = os.path.abspath('img/icon.gif')
addBatch = os.path.abspath('img/icon.gif')
verifyInventory = os.path.abspath('img/icon.gif')
updateInventory = os.path.abspath('img/icon.gif')
viewInventory = os.path.abspath('img/icon.gif')
viewMashes = os.path.abspath('img/icon.gif')
viewCalculators = os.path.abspath('img/icon.gif')

class recipeEditor(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: recipeEditor.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_3 = wx.Panel(self, -1, style=wx.SIMPLE_BORDER|wx.TAB_TRAVERSAL)
        self.panel_2 = wx.Panel(self, -1, style=wx.SIMPLE_BORDER|wx.TAB_TRAVERSAL)
        self.panel_1 = wx.Panel(self, -1, style=wx.SIMPLE_BORDER|wx.TAB_TRAVERSAL)
        
        # Menu Bar
        self.recipeEditor_menubar = wx.MenuBar()
        self.fileMenu = wx.Menu()
        self.fileMenu.Append(1001, "&Quit", "Terminate the recipe editor", wx.ITEM_NORMAL)
        self.recipeEditor_menubar.Append(self.fileMenu, "&File")
        self.SetMenuBar(self.recipeEditor_menubar)
        # Menu Bar end
        self.recipeEditor_statusbar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.recipeEditor_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_TEXT)
        self.SetToolBar(self.recipeEditor_toolbar)
        self.recipeEditor_toolbar.AddLabelTool(100, "New Recipe", wx.Bitmap(newRecipe,wx.BITMAP_TYPE_ANY), wx.Bitmap(newRecipe,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "New Recipe", "Start a new recipe")
        self.recipeEditor_toolbar.AddLabelTool(101, "Add Batch", wx.Bitmap(addBatch,wx.BITMAP_TYPE_ANY), wx.Bitmap(addBatch,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "Add Batch", "Add a new batch of the current recipe")
        self.recipeEditor_toolbar.AddSeparator()
        self.recipeEditor_toolbar.AddLabelTool(102, "Verify Inventory", wx.Bitmap(verifyInventory,wx.BITMAP_TYPE_ANY), wx.Bitmap(verifyInventory,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "Verify Inventory", "Verify your inventory contains all the ingredients for the batch")
        self.recipeEditor_toolbar.AddLabelTool(103, "Update Inventory", wx.Bitmap(updateInventory,wx.BITMAP_TYPE_ANY), wx.Bitmap(updateInventory,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "Update Inventory", "Remove the items for the current batch from your inventory")
        self.recipeEditor_toolbar.AddLabelTool(104, "View Inventory", wx.Bitmap(viewInventory,wx.BITMAP_TYPE_ANY), wx.Bitmap(viewInventory,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "View Inventory", "Launch the inventory editor")
        self.recipeEditor_toolbar.AddSeparator()
        self.recipeEditor_toolbar.AddLabelTool(105, "View Mashes", wx.Bitmap(viewMashes,wx.BITMAP_TYPE_ANY), wx.Bitmap(viewMashes,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "View Mashes", "Launch the mash editor")
        self.recipeEditor_toolbar.AddSeparator()
        self.recipeEditor_toolbar.AddLabelTool(106, "View Calculators", wx.Bitmap(viewCalculators,wx.BITMAP_TYPE_ANY), wx.Bitmap(viewCalculators,wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "View Calculators", "Launch the calculators")
        # Tool Bar end
        self.label_1 = wx.StaticText(self.panel_1, -1, "Name:")
        self.nameCtrl = wx.TextCtrl(self.panel_1, -1, "")
        self.label_1_copy = wx.StaticText(self.panel_1, -1, "Style:")
        self.choice_1 = wx.Choice(self.panel_1, -1, choices=["Beer", "Awesome"])
        self.label_1_copy_1 = wx.StaticText(self.panel_1, -1, "Brewer:")
        self.brewerCtrl = wx.TextCtrl(self.panel_1, -1, "")
        self.label_2 = wx.StaticText(self.panel_2, -1, "Ingredients")
        self.list_ctrl_1 = wx.ListCtrl(self.panel_2, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.addItem = wx.Button(self.panel_2, -1, "Add")
        self.deleteItem = wx.Button(self.panel_2, -1, "&Delete")
        self.button_1 = wx.Button(self.panel_3, -1, "Efficiency:")
        self.efficencyCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.label_4 = wx.StaticText(self.panel_3, -1, "%")
        self.label_3 = wx.StaticText(self.panel_3, -1, "Batch Size:")
        self.batchSizeCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.batchSizeChoiceCtrl = wx.Choice(self.panel_3, -1, choices=["Gal", "l"])
        self.label_3_copy = wx.StaticText(self.panel_3, -1, "OG:")
        self.OGEstCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.OGEstStyleCtrl = wx.StaticText(self.panel_3, -1, "Style: ")
        self.label_3_copy_1 = wx.StaticText(self.panel_3, -1, "FG:")
        self.FGEstCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.FGEstStyleCtrl = wx.StaticText(self.panel_3, -1, "Style: ")
        self.label_3_copy_2 = wx.StaticText(self.panel_3, -1, "Color:")
        self.colorEstCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.colorEstStyleCtrl = wx.StaticText(self.panel_3, -1, "Style: ")
        self.label_3_copy_3 = wx.StaticText(self.panel_3, -1, "IBU:")
        self.IBUEstCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.IBUEstStyleCtrl = wx.StaticText(self.panel_3, -1, "Style: ")
        self.label_3_copy_4 = wx.StaticText(self.panel_3, -1, "Bitterness Ratio:")
        self.bitternessRatioCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.bitternessRatioStyleCtrl = wx.StaticText(self.panel_3, -1, "Style: ")
        self.label_3_copy_5 = wx.StaticText(self.panel_3, -1, "ABV:")
        self.ABVEstCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.ABVEstStyleCtrl = wx.StaticText(self.panel_3, -1, "Style: ")
        self.label_3_copy_6 = wx.StaticText(self.panel_3, -1, "ABW:")
        self.ABWEstCtrl = wx.TextCtrl(self.panel_3, -1, "")
        self.label_4_copy = wx.StaticText(self.panel_3, -1, "%")
        self.label_3_copy_7 = wx.StaticText(self.panel_3, -1, "Calories:")
        self.caloriesEstCtrl = wx.TextCtrl(self.panel_3, -1, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnQuit, id=1001)
        self.Bind(wx.EVT_TOOL, self.NewRecipe, id=100)
        self.Bind(wx.EVT_TOOL, self.AddBatch, id=101)
        self.Bind(wx.EVT_TOOL, self.VerifyInventory, id=102)
        self.Bind(wx.EVT_TOOL, self.UpdateInventory, id=103)
        self.Bind(wx.EVT_TOOL, self.ViewInventory, id=104)
        self.Bind(wx.EVT_TOOL, self.ViewMashes, id=105)
        self.Bind(wx.EVT_TOOL, self.ViewCalculators, id=106)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: recipeEditor.__set_properties
        self.SetTitle("Recipe Editor")
        self.SetSize((1024, 768))
        self.recipeEditor_statusbar.SetStatusWidths([-1])
        # statusbar fields
        recipeEditor_statusbar_fields = ["recipeEditor_statusbar"]
        for i in range(len(recipeEditor_statusbar_fields)):
            self.recipeEditor_statusbar.SetStatusText(recipeEditor_statusbar_fields[i], i)
        self.recipeEditor_toolbar.Realize()
        self.choice_1.SetSelection(0)
        self.batchSizeChoiceCtrl.SetSelection(0)
        self.colorEstStyleCtrl.SetMinSize((41, 17))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: recipeEditor.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(10, 3, 0, 0)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.label_1, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(self.nameCtrl, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(self.label_1_copy, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(self.choice_1, 1, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(self.label_1_copy_1, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(self.brewerCtrl, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 0, wx.ALL|wx.EXPAND, 5)
        sizer_4.Add(self.label_2, 0, wx.LEFT|wx.RIGHT|wx.TOP|wx.ADJUST_MINSIZE, 5)
        sizer_4.Add(self.list_ctrl_1, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
        sizer_5.Add(self.addItem, 0, wx.ALL|wx.ADJUST_MINSIZE, 5)
        sizer_5.Add(self.deleteItem, 0, wx.ALL|wx.ADJUST_MINSIZE, 5)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_4)
        sizer_3.Add(self.panel_2, 1, wx.ALL|wx.EXPAND, 5)
        grid_sizer_1.Add(self.button_1, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.efficencyCtrl, 1, wx.ALL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_4, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_3, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.batchSizeCtrl, 1, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.batchSizeChoiceCtrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_3_copy, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.OGEstCtrl, 1, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.OGEstStyleCtrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_3_copy_1, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.FGEstCtrl, 1, wx.ALL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.FGEstStyleCtrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_3_copy_2, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.colorEstCtrl, 1, wx.ALL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.colorEstStyleCtrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_3_copy_3, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.IBUEstCtrl, 1, wx.ALL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.IBUEstStyleCtrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_3_copy_4, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.bitternessRatioCtrl, 1, wx.ALL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.bitternessRatioStyleCtrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_3_copy_5, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.ABVEstCtrl, 1, wx.ALL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.ABVEstStyleCtrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_3_copy_6, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.ABWEstCtrl, 1, wx.ALL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_4_copy, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.label_3_copy_7, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 2)
        grid_sizer_1.Add(self.caloriesEstCtrl, 1, wx.ALL|wx.ADJUST_MINSIZE, 2)
        self.panel_3.SetSizer(grid_sizer_1)
        sizer_3.Add(self.panel_3, 0, wx.ALL|wx.EXPAND, 5)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.SetSize((1024, 768))
        # end wxGlade

    def OnQuit(self, event): # wxGlade: recipeEditor.<event_handler>
        print "Event handler `OnQuit' not implemented!"
        event.Skip()

    def NewRecipe(self, event): # wxGlade: recipeEditor.<event_handler>
        print "Event handler `NewRecipe' not implemented!"
        event.Skip()

    def AddBatch(self, event): # wxGlade: recipeEditor.<event_handler>
        print "Event handler `AddBatch' not implemented!"
        event.Skip()

    def VerifyInventory(self, event): # wxGlade: recipeEditor.<event_handler>
        print "Event handler `VerifyInventory' not implemented!"
        event.Skip()

    def UpdateInventory(self, event): # wxGlade: recipeEditor.<event_handler>
        print "Event handler `UpdateInventory' not implemented!"
        event.Skip()

    def ViewInventory(self, event): # wxGlade: recipeEditor.<event_handler>
        print "Event handler `ViewInventory' not implemented!"
        event.Skip()

    def ViewMashes(self, event): # wxGlade: recipeEditor.<event_handler>
        print "Event handler `ViewMashes' not implemented!"
        event.Skip()

    def ViewCalculators(self, event): # wxGlade: recipeEditor.<event_handler>
        print "Event handler `ViewCalculators' not implemented!"
        event.Skip()

# end of class recipeEditor


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    recipeEditor = recipeEditor(None, -1, "")
    app.SetTopWindow(recipeEditor)
    recipeEditor.Show()
    app.MainLoop()
